/**
 * Zod Schemas for Gemini Structured Outputs
 *
 * These schemas ensure type-safe responses from Gemini API
 */

import { z } from 'zod';

/**
 * CEFR Level enum
 */
export const CEFRLevel = z.enum(['A1', 'A2', 'B1', 'B2', 'C1', 'C2']);
export type CEFRLevel = z.infer<typeof CEFRLevel>;

/**
 * Schema for assessment questions generated by Gemini
 */
export const AssessmentQuestionSchema = z.object({
  hebrew: z.string().describe('The Hebrew text/word to test'),
  russian: z.string().describe('The question text in Russian'),
  options: z.array(z.string()).length(4).describe('4 multiple choice options in Russian'),
  correctIndex: z.number().min(0).max(3).describe('Index of the correct answer (0-3)'),
  level: CEFRLevel.describe('CEFR level this question tests'),
});

export const AssessmentQuestionsSchema = z.object({
  questions: z.array(AssessmentQuestionSchema).min(5).max(10),
});

export type AssessmentQuestion = z.infer<typeof AssessmentQuestionSchema>;
export type AssessmentQuestions = z.infer<typeof AssessmentQuestionsSchema>;

/**
 * Schema for level analysis after assessment
 */
export const LevelAnalysisSchema = z.object({
  level: CEFRLevel.describe('The assigned CEFR level'),
  reasoning: z.string().describe('Explanation of why this level was assigned'),
  strengths: z.array(z.string()).describe('User strengths observed'),
  recommendations: z.array(z.string()).describe('Recommendations for learning'),
});

export type LevelAnalysis = z.infer<typeof LevelAnalysisSchema>;

/**
 * Schema for Hebrew word translation
 */
export const WordTranslationSchema = z.object({
  hebrew: z.string().describe('The original Hebrew word'),
  russian: z.string().describe('Primary Russian translation'),
  alternativeTranslations: z.array(z.string()).optional().describe('Alternative translations if applicable'),
  partOfSpeech: z.string().describe('Part of speech (noun, verb, adjective, etc.)'),
  exampleHebrew: z.string().optional().describe('Example sentence in Hebrew'),
  exampleRussian: z.string().optional().describe('Example sentence translation in Russian'),
});

export const TranslationBatchSchema = z.object({
  translations: z.array(WordTranslationSchema),
});

export type WordTranslation = z.infer<typeof WordTranslationSchema>;
export type TranslationBatch = z.infer<typeof TranslationBatchSchema>;

/**
 * Schema for CEFR level assignment
 */
export const LevelAssignmentSchema = z.object({
  word: z.string().describe('The Hebrew word'),
  level: CEFRLevel.describe('Assigned CEFR level'),
  reasoning: z.string().describe('Why this level was assigned'),
});

export const LevelAssignmentBatchSchema = z.object({
  assignments: z.array(LevelAssignmentSchema),
});

export type LevelAssignment = z.infer<typeof LevelAssignmentSchema>;
export type LevelAssignmentBatch = z.infer<typeof LevelAssignmentBatchSchema>;

/**
 * Schema for exercise distractor generation
 */
export const ExerciseDistractorsSchema = z.object({
  distractors: z.array(z.string()).min(3).max(3).describe('3 plausible but incorrect options'),
});

export type ExerciseDistractors = z.infer<typeof ExerciseDistractorsSchema>;
